name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Test
      run: cargo test --verbose
  package:
    needs: test 
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v4
      - name: login
        uses: docker/login-action@v3
        with: 
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Docker build
        run: docker build -t ghcr.io/modulus/random-name-generator-2:latest -f Dockerfile .
      - name: Docker push
        run: docker push ghcr.io/modulus/random-name-generator-2:latest





# https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
