name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  package:
    needs: build 
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v4
      - name: login
        uses: docker/login-action@v3
        with: 
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Docker build
        run: docker build -t ghcr.io/modulus/random-name-generator-2:latest -f Dockerfile .
      - name: Docker push
        run: docker push ghcr.io/modulus/random-name-generator-2:latest




